version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOt-url=http://grafana.ablack94.dev/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '192.168.1.11:9002:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
volumes:
  grafana_storage: {}

